### ISSUE TITLE
Support non-GitHub.com repositories

### ISSUE THREAD

**Issue by vermiculus** [vermiculus/magithub#34]
`hub` works for GitHub Enterprise, but Magithub doesn't. Let's fix that! We should only need to modify `magithub-github-repository-p`. (From #33)

Thought: could use any available git variables or hub config variables to see if it should be enabled. At the very least, we should be able to thumb through `.config/hub` to see if any of the servers there match the origin we're in right now.

**Comment by vermiculus** [comment]
@saintaardvark It doesn't look like I have the same `[hub]` section in `~/.gitconfig`. The only thing that mentions `github.com` is in `~/.config/hub`:

```yaml
---
github.com:
- protocol: https
  user: vermiculus
  oauth_token: <nope />
```

I'm going to get into `hub`'s implementation, but what version of `hub` are you working off of?
